    run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        run: '-c Release -o "C:\Program Files\dotnet\myapp"'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
@@ -39,21 +39,21 @@ jobs:
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CE5156DE4D424286B93514BFA3C4881A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3117C6A044FA4FE8A83C139BD2879F19 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F80A0BED88B640ADA34AA8754E03FF17 }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CE5156DE4D424286B93514BFA3C4881A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3117C6A044FA4FE8A83C139BD2879F19 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F80A0BED88B640ADA34AA8754E03FF17 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
@@ -62,4 +62,4 @@ jobs:
          app-name: 'teste-appweb'
          slot-name: 'Production'
          package: .
